# Site settings
title: the_incubator
email: khandori@g.ucla.edu
description: > # this means to ignore newlines until "baseurl:"
  an incubator for kiwon
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joshuafromkorea.github.io" # the base hostname & protocol for your site
# twitter_username: username
# github_username: username

# Build settings
#markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

#gems
gems: [jekyll-mermaid]


mermaid:
        src: '/js/mermaid.js'

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
